### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by vishpat** [adtech-labs/bayes_logistic#5]
Hit the following exception while using the bayes_logistic module

vpati011@Shlokster:~/Downloads$ python parkisons.py 
Traceback (most recent call last):
  File "parkisons.py", line 71, in <module>
    w_prior, H_prior, solver = 'BFGS')
  File "/usr/local/lib/python2.7/dist-packages/bayes_logistic/bayes_logistic.py", line 432, in fit_bayes_logistic
    method='BFGS', options={'maxiter': maxiter})
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/_minimize.py", line 444, in minimize
    return _minimize_bfgs(fun, x0, args, jac, callback, **options)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 913, in _minimize_bfgs
    gfk = myfprime(x0)
  File "/usr/local/lib/python2.7/dist-packages/scipy/optimize/optimize.py", line 292, in function_wrapper
    return function(*(wrapper_args + args))
  File "/usr/local/lib/python2.7/dist-packages/bayes_logistic/bayes_logistic.py", line 223, in g_log_posterior_small
    grad_log_post = np.dot(X.T, weights * (mu - y)) + np.dot(H, (w - wprior))
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

The code to reproduce the issue can be found at
http://pastebin.com/KV16bkXt

**Comment by mariusvniekerk** [comment]
Can you run this bit with %debug in a notebook and see which part of this is actually None?
